/**
 * Minimal mock dictionary for tests.
 * Only includes keys used by the components under test.
 */
export const mockDict = {
  meta: {
    title: "KobKlein — Digital Financial Freedom for Haiti",
    description: "Send money instantly.",
  },
  nav: {
    home: "Home",
    about: "About",
    howItWorks: "How It Works",
    compliance: "Compliance",
    download: "Download",
    distributor: "Become a Distributor",
    kcard: "K-Card",
    login: "Sign In",
  },
  hero: {
    badge: "The Future of Digital Finance in Haiti",
    title: "Your Money. Your Power. No Banks.",
    subtitle: "The secure digital wallet connecting Haiti and its diaspora worldwide.",
    description: "A secure, cashless digital wallet system.",
    cta: "Get Started",
    ctaSecondary: "See How It Works",
    stats: {
      users: "100K+",
      usersLabel: "Active Users",
      transfers: "$50M+",
      transfersLabel: "Transferred",
      countries: "15+",
      countriesLabel: "Countries",
      uptime: "99.9%",
      uptimeLabel: "Uptime",
    },
    features: {
      security: {
        title: "Bank-Grade Security",
        description: "Enterprise encryption and real-time fraud prevention.",
      },
      instant: {
        title: "Instant Processing",
        description: "Real-time transactions that arrive in seconds.",
      },
      fees: {
        title: "Zero Hidden Fees",
        description: "Transparent pricing with no surprises.",
      },
    },
  },
  features: {
    title: "Why KobKlein?",
    subtitle: "Everything you need for modern digital payments",
    instant: { title: "K-Pay Instant Transfers", description: "Send and receive money in real-time." },
    security: { title: "Bank-Grade Security", description: "Advanced encryption." },
    global: { title: "K-Link Global Network", description: "Connect with the Haitian diaspora worldwide." },
    card: { title: "K-Card Virtual Card", description: "Shop Netflix, Amazon, and more." },
    lowFees: { title: "Lowest Fees Guaranteed", description: "K-Pay transfers are free." },
    kcode: { title: "K-Code & K-Scan", description: "Share a 6-digit rotating code." },
  },
  comparison: {
    title: "Compare & Save",
    subtitle: "See why KobKlein is the smartest way to send money to Haiti",
    route: "Route",
    westernUnion: "Western Union",
    moneyGram: "MoneyGram",
    kobklein: "KobKlein",
    usToHaiti: "US → Haiti ($100)",
    p2p: "KobKlein → KobKlein",
    cashOut: "Cash-out at Agent",
    onlinePurchase: "K-Card Purchase",
    free: "FREE",
    na: "N/A",
  },
  footer: {
    tagline: "Your money, in your hands.",
    product: "Product",
    company: "Company",
    legal: "Legal",
    about: "About",
    howItWorks: "How It Works",
    pricing: "Pricing",
    faq: "FAQ",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    compliance: "Compliance",
    aml: "AML Policy",
    contact: "Contact Us",
    careers: "Careers",
    press: "Press",
    copyright: "KobKlein Inc. All rights reserved.",
  },
  cta: {
    title: "Ready to Join the Revolution?",
    subtitle: "Download KobKlein today.",
    button: "Get Started Free",
  },
} as any;
